//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 04:48:52 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Form", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dbconnect.xml.dao;
