//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 07:53:50 PM CST 
//


package dbconnect.xml.dao;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariadicBooleanResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VariadicBooleanResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Form}response">
 *       &lt;sequence>
 *         &lt;element name="optionResponse" type="{http://www.example.org/Form}VariadicBooleanEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VariadicBooleanResponse", propOrder = {
    "optionResponse"
})
public class VariadicBooleanResponse
    extends Response
{

    protected List<VariadicBooleanEntry> optionResponse;

    /**
     * Gets the value of the optionResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariadicBooleanEntry }
     * 
     * 
     */
    public List<VariadicBooleanEntry> getOptionResponse() {
        if (optionResponse == null) {
            optionResponse = new ArrayList<VariadicBooleanEntry>();
        }
        return this.optionResponse;
    }

}
